package com.gmail.vexonelite.jetpack.study.viewmodels


object BaseErrorCodes {

    const val UNKNOWN_ERROR = "00000"

    const val ILLEGAL_ARGUMENT_ERROR = "99998"

    const val RUN_PREDICATION_ERROR = "99995"

    const val JSON_WRAPPING_FAILURE = "99989"
    const val JSON_PARSING_FAILURE = "99988"
    const val NO_SPECIFIED_KEY_IN_JSON = "99987"

    const val AES_ENCRYPTION_ERROR = "99979"
    const val AES_DECRYPTION_ERROR = "99978"

    const val IMAGE_CONVERSION_ERROR = "99959"
    const val DATE_ITEM_GENERATION_FAILURE = "99958"
    const val DISPLAY_ERROR_CODE_AND_MESSAGE = "99957"
    const val XML_PARSING_FAILURE = "99956"
    const val FACEBOOK_GRAPH_RESPONSE_ERROR = "99955"
    const val FACEBOOK_LOGIN_ERROR = "99954"
    const val RX_MAYBE_ON_COMPLETE = "99953"
    const val OUT_OF_MEMORY = "99952"

    const val UNSUPPORTED_ENCODING = "99951"

    const val INVALID_REQUEST_CODE = "99950"

    const val NETWORK_IS_DISCONNECTED = "99949"

    const val THREAD_INTERRUPTED = "99948"

    const val CALCULATE_DIFF_RESULT_ERROR = "99947"

    const val NULL_POINTER_ERROR = "99946"

    const val DEFAULT_UNIT_TEST_ERROR = "99945"

    //const val JOB_CANCELLATION_REMINDER = "99944"

    const val INTERNAL_GENERATION_ERROR = "99944";
    const val INTERNAL_CONVERSION_ERROR = "99943";
    const val INTERNAL_FILTERING_ERROR = "99942";
    const val INTERNAL_PROCESS_ERROR = "99941";

    const val ASYNC_TASK_STILL_RUNS = "99940"
    const val FAIL_TO_SEND_EMAIL = "99939";
}


object IoErrorCodes {
    const val INPUT_STREAM_CREATION_FAILURE = "89999"
    const val OUTPUT_STREAM_CREATION_FAILURE = "89998"
    const val FILE_COPY_FAILURE = "89997"
    const val FILE_PROVIDER_GET_URI_FAILURE = "89996"
    const val CONTENT_RESOLVER_INSERT_FAILURE = "89995"
    const val CONTENT_RESOLVER_OUTPUT_STREAM_OPEN_FAILURE = "89994"
    const val CONTENT_RESOLVER_QUERY_FAILURE = "89993"
    const val FILE_URI_CREATION_FAILURE = "89983"
    const val FILE_CREATION_FAILURE = "89982"
    const val FILE_REMOVAL_FAILURE = "89981"

    const val FAIL_TO_WRITE_TO_FILE = "89980"
    const val FAIL_TO_READ_FROM_FILE = "89979"

    const val GENERAL_OPERATION_FAILURE = "89901"
}

